-- Business question : What is the total revenue generated by each product?
-- Concept           : Multi-table JOIN, GROUP BY

SELECT
    p.product_id,
    p.product_name,
    p.category_id,
    SUM(oi.line_total) AS total_revenue
FROM products p
INNER JOIN order_items oi ON p.product_id = oi.product_id
INNER JOIN orders o       ON oi.order_id  = o.order_id
WHERE o.order_status = 'Delivered'
GROUP BY p.product_id, p.product_name, p.category_id
ORDER BY total_revenue DESC;